# Generated by Django 5.0.6 on 2024-07-07 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        verbose_name="Введите электронную почту",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Полное Ф.И.О."),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(verbose_name="Активна ли рассылка")),
                (
                    "start_date",
                    models.DateTimeField(
                        default=datetime.datetime.now,
                        verbose_name="Дата и время начала рассылки",
                    ),
                ),
                (
                    "last_sent_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата и время последней рассылки",
                    ),
                ),
                (
                    "periodicity",
                    models.IntegerField(
                        choices=[
                            (1440, "Каждый день"),
                            (10080, "Каждую неделю"),
                            (43200, "Каждый месяц"),
                        ],
                        default="1440",
                        verbose_name="Периодичность рассылки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("started", "Начата"),
                            ("finished", "Завершена"),
                        ],
                        default="created",
                        max_length=50,
                        verbose_name="Статус рассылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "permissions": [
                    ("deactivate_mailing", "Может деактивировать рассылку"),
                    ("view_all_mailings", "Может просматривать все рассылки"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время начала рассылки"
                    ),
                ),
                (
                    "status",
                    models.CharField(max_length=50, verbose_name="Статус рассылки"),
                ),
                (
                    "server_response",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ответ сервера"
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
                "permissions": [
                    ("view_mailing", "Может просматривать попытки рассылки")
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Тема")),
                ("body", models.TextField(verbose_name="Текст")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
