# Generated by Django 5.0.6 on 2024-07-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="active",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Активирована"
            ),
        ),
    ]
