# Generated by Django 5.0.6 on 2024-05-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_customer', '0004_alter_client_options_alter_client_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий'),
        ),
    ]
