# Generated by Django 5.0.6 on 2024-06-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_customer', '0006_alter_mailing_start_date_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
