# Generated by Django 5.0.6 on 2024-07-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_customer", "0007_alter_mailing_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="periodicity",
            field=models.CharField(
                choices=[
                    (1, "1 минута"),
                    (1440, "Каждый день"),
                    (10080, "Каждую неделю"),
                    (43200, "Каждый месяц"),
                ],
                default="daily",
                max_length=50,
                verbose_name="Периодичность рассылки",
            ),
        ),
    ]
