# Generated by Django 5.0.6 on 2024-06-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_customer', '0007_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(related_name='mailings', to='service_customer.client'),
        ),
    ]
