# Generated by Django 5.0.6 on 2024-07-01 16:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_customer", "0011_alter_mailing_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
        migrations.AlterField(
            model_name="mailing",
            name="clients",
            field=models.ManyToManyField(
                related_name="mailings",
                to="service_customer.client",
                verbose_name="Клиенты",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="service_customer.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("daily", "Каждый день"),
                    ("weekly", "Каждую неделю"),
                    ("monthly", "Каждый месяц"),
                ],
                max_length=50,
                verbose_name="Периодичность рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime.now,
                verbose_name="Дата и время начала рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("started", "Начата"),
                    ("finished", "Завершена"),
                ],
                max_length=50,
                verbose_name="Статус рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="attempt_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата и время начала рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="mailing",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="service_customer.mailing",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="server_response",
            field=models.TextField(blank=True, null=True, verbose_name="Ответ сервера"),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(max_length=50, verbose_name="Статус рассылки"),
        ),
    ]
