# Generated by Django 5.0.6 on 2024-07-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "service_customer",
            "0012_alter_mailingattempt_options_alter_mailing_clients_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("daily", "Каждый день"),
                    ("weekly", "Каждую неделю"),
                    ("monthly", "Каждый месяц"),
                ],
                default="daily",
                max_length=50,
                verbose_name="Периодичность рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("started", "Начата"),
                    ("finished", "Завершена"),
                ],
                default="created",
                max_length=50,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
